Name:                   k6-operator-controller-manager
Namespace:              k6-operator-system
CreationTimestamp:      Wed, 04 Jan 2023 15:19:31 +0900
Labels:                 control-plane=controller-manager
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               control-plane=controller-manager
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           control-plane=controller-manager
  Service Account:  k6-operator-controller
  Containers:
    kube-rbac-proxy:
      Image:      gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
      Port:       8443/TCP
      Host Port:  0/TCP
      Args:
        --secure-listen-address=0.0.0.0:8443
        --upstream=http://127.0.0.1:8080/
        --logtostderr=true
        --v=10
      Environment:  <none>
      Mounts:       <none>
    manager:
      Image:      ghcr.io/grafana/operator:latest
      Port:       <none>
      Host Port:  <none>
      Command:
        /manager
      Args:
        --metrics-addr=127.0.0.1:8080
        --enable-leader-election
      Limits:
        cpu:     100m
        memory:  100Mi
      Requests:
        cpu:        100m
        memory:     50Mi
      Environment:  <none>
      Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   k6-operator-controller-manager-5c8f6fb97f (1/1 replicas created)
Events:          <none>