---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k6-operator-manager-rolebinding
subjects:
  - kind: ServiceAccount
    name: k6-operator-controller
    namespace: k6-operator-system
roleRef:
  kind: ClusterRole
  name: k6-operator-manager-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: k6-operator-proxy-rolebinding
subjects:
  - kind: ServiceAccount
    name: k6-operator-controller
    namespace: k6-operator-system
roleRef:
  kind: ClusterRole
  name: k6-operator-proxy-role
  apiGroup: rbac.authorization.k8s.io