apiVersion: v1
kind: Namespace
metadata:
  name: k6-operator-system
  labels:
    app.kubernetes.io/name: k6-operator
    control-plane: controller-manager
    kubernetes.io/metadata.name: k6-operator-system