apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: k6-operator-system
  name: k6-operator-leader-election-role
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]