apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k6-operator-leader-election-rolebinding
  namespace: k6-operator-system
subjects:
  - kind: ServiceAccount
    name: k6-operator-controller
    namespace: k6-operator-system
roleRef:
  kind: Role
  name: k6-operator-leader-election-role
  apiGroup: rbac.authorization.k8s.io