apiVersion: v1
kind: Service
metadata:
  name: k6-operator-controller-manager-metrics-service
  namespace: k6-operator-system
  labels:
    control-plane: controller-manager
spec:
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4
  selector:
    control-plane: controller-manager
  ports:
    - name: https
      protocol: TCP
      port: 8443
      targetPort: https
